Repository prebid/prebid-cache-java, pull requests merged in 2024-08, with the labels that each got.

#139 Test: `Storage-module`
  src/test/kotlin/org/prebid/cache/functional/StorageSpec.kt
  src/test/kotlin/org/prebid/cache/functional/service/PrebidCacheApi.kt
  src/test/kotlin/org/prebid/cache/functional/testcontainers/PrebidCacheContainerConfig.kt
Labels: tests

#141 Add functional tests for the new Apache Ignite feature
  src/test/kotlin/org/prebid/cache/functional/ApacheIgniteCacheSpec.kt
  src/test/kotlin/org/prebid/cache/functional/BaseSpec.kt
  src/test/kotlin/org/prebid/cache/functional/testcontainers/ContainerDependencies.kt
  src/test/kotlin/org/prebid/cache/functional/testcontainers/PrebidCacheContainerConfig.kt
  src/test/kotlin/org/prebid/cache/functional/testcontainers/container/ApacheIgniteContainer.kt
  src/test/kotlin/org/prebid/cache/functional/testcontainers/container/PrebidCacheContainer.kt
  src/test/resources/functional/ignite-config.xml
Labels: tests, do not port

#140 Add Apache Ignite Repo
  README.md
  docs/differenceBetweenPBCGo-and-Java.md
  pom.xml
  src/main/java/org/prebid/cache/config/RepositoryConfig.java
  src/main/java/org/prebid/cache/repository/ignite/IgniteConfiguration.java
  src/main/java/org/prebid/cache/repository/ignite/IgniteConfigurationProperties.java
  src/main/java/org/prebid/cache/repository/ignite/IgniteRepositoryImpl.java
  src/test/java/org/prebid/cache/repository/ignite/IgniteRepositoryImplTest.java
  src/test/kotlin/org/prebid/cache/functional/ApacheIgniteCacheSpec.kt
  src/test/kotlin/org/prebid/cache/functional/BaseSpec.kt
  src/test/kotlin/org/prebid/cache/functional/testcontainers/ContainerDependencies.kt
  src/test/kotlin/org/prebid/cache/functional/testcontainers/PrebidCacheContainerConfig.kt
  src/test/kotlin/org/prebid/cache/functional/testcontainers/container/ApacheIgniteContainer.kt
  src/test/kotlin/org/prebid/cache/functional/testcontainers/container/PrebidCacheContainer.kt
  src/test/resources/functional/ignite-config.xml
Labels: do not port

#143 Housekeeping: Switch JaCoCo code coverage report generation to package phase
  pom.xml
Labels: do not port
