Repository prebid/prebid-cache-java, pull requests merged in 2025-02, with the labels that each got.

#142 Add functional tests for prevent external
  src/test/kotlin/org/prebid/cache/functional/AerospikeCacheSpec.kt
  src/test/kotlin/org/prebid/cache/functional/ApacheIgniteCacheSpec.kt
  src/test/kotlin/org/prebid/cache/functional/AuthenticationCacheSpec.kt
  src/test/kotlin/org/prebid/cache/functional/BaseSpec.kt
  src/test/kotlin/org/prebid/cache/functional/GeneralCacheSpec.kt
  src/test/kotlin/org/prebid/cache/functional/ProxyCacheHostSpec.kt
  src/test/kotlin/org/prebid/cache/functional/RedisCacheSpec.kt
  src/test/kotlin/org/prebid/cache/functional/SecondaryCacheSpec.kt
  src/test/kotlin/org/prebid/cache/functional/service/PrebidCacheApi.kt
  src/test/kotlin/org/prebid/cache/functional/testcontainers/PrebidCacheContainerConfig.kt
Labels: tests, do not port

#157 Add functional tests for external-uuid-security
  src/test/kotlin/org/prebid/cache/functional/AuthenticationCacheSpec.kt
  src/test/kotlin/org/prebid/cache/functional/testcontainers/PrebidCacheContainerConfig.kt
Labels: tests

#158 Add documentation for API key security parameters and metrics
  docs/config.md
  docs/metrics.md
Labels: do not port
